INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Aquaman", "El poder más reconocido de Aquaman es la capacidad telepática para comunicarse con la vida marina, la cual puede convocar a grandes distancias.", "aquaman.png", "1941-11-01", "DC");
INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Batman", "Los rasgos principales de Batman se resumen en «destreza física, habilidades deductivas y obsesión». La mayor parte de las características básicas de los cómics han variado por las diferentes interpretaciones que le han dado al personaje.", "batman.png", "1939-05-01", "DC");
INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Daredevil", "Al haber perdido la vista, los cuatro sentidos restantes de Daredevil fueron aumentados por la radiación a niveles superhumanos, en el accidente que tuvo cuando era niño. A pesar de su ceguera, puede 'ver' a través de un 'sexto sentido' que le sirve como un radar similar al de los murciélagos.", "daredevil.png", "1964-01-01", "Marvel");
INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Hulk", "Su principal poder es su capacidad de aumentar su fuerza hasta niveles prácticamente ilimitados a la vez que aumenta su furia. Dependiendo de qué personalidad de Hulk esté al mando en ese momento (el Hulk Banner es el más débil, pero lo compensa con su inteligencia).", "hulk.png", "1962-05-01", "Marvel");
INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Linterna Verde", "Poseedor del anillo de poder que posee la capacidad de crear manifestaciones de luz sólida mediante la utilización del pensamiento. Es alimentado por la Llama Verde (revisada por escritores posteriores como un poder místico llamado Starheart), una llama mágica contenida en dentro de un orbe (el orbe era en realidad un meteorito verde de metal que cayó a la Tierra, el cual encontró un fabricante de lámparas llamado Chang)", "linterna-verde.png", "1940-06-01", "DC");
INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Spider-Man", "Tras ser mordido por una araña radiactiva, obtuvo los siguientes poderes sobrehumanos, una gran fuerza, agilidad, poder trepar por paredes. La fuerza de Spider-Man le permite levantar 10 toneladas o más. Gracias a esta gran fuerza Spider-Man puede realizar saltos íncreibles. Un 'sentido arácnido', que le permite saber si un peligro se cierne sobre él, antes de que suceda. En ocasiones este puede llevar a Spider-Man al origen del peligro.", "spiderman.png", "1962-08-01", "Marvel");
INSERT INTO heroes(nombre, biografia, ruta_imagen, aparicion, casa) VALUES("Wolverine", "En el universo ficticio de Marvel, Wolverine posee poderes regenerativos que pueden curar cualquier herida, por mortal que ésta sea, además ese mismo poder hace que sea inmune a cualquier enfermedad existente en la Tierra y algunas extraterrestres . Posee también una fuerza sobrehumana, que si bien no se compara con la de otros superhéroes como Hulk, sí sobrepasa la de cualquier humano.", "wolverine.png", "1974-11-01", "Marvel");

INSERT INTO usuarios(usuario, contrasena) VALUES("carlos", "12345");
INSERT INTO usuarios(usuario, contrasena) VALUES("pedro", "1234");